### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by DonkeyMonkeyHit** [PlutoSolutions/KonasEnhanced#8]
pi zdec cho delat(((

**Comment by mr-nv** [comment]
-noverify

**Comment by DonkeyMonkeyHit** [comment]
Да, я уже прописывал это в аргументы. Крашит на моменте: [Client thread/INFO] [minecraft/Minecraft]: Setting user: Ismaquin

**Comment by mr-nv** [comment]
скинь лог полный и какой лаунчер используешь

**Comment by mr-nv** [comment]
и куда все скинул

**Comment by DonkeyMonkeyHit** [comment]
Лаунчер TLauncher (играю на лицензии), konsa_new в .minecraft, konsafree в .minecraft/mods
Фулл лог: https://gist.github.com/DonkeyMonkeyHit/ca18a082e2f9c9cbbc79b21295866e74

**Comment by mr-nv** [comment]
Caused by: java.lang.NoClassDefFoundError: Class23
эта хуйня из за того что у тебя все же нет -noverify

мне кажется что эта проблема из за тлаунчера, они хуйню какую то сделали и у меня например метеор клиент не грузился на нем
если у тебя есть лицуха то скачай multimc и попробуй в нем
если нет то найди другой лаунчер

**Comment by mr-nv** [comment]
>играю на лицензии
нахуй тебе тлаунчер на лицензионном акке я хуй знает
качай multimc (https://multimc.org), в будущем еще пригодится

**Comment by DonkeyMonkeyHit** [comment]
MMC по непонятным не причинам крашит если включен forge

**Comment by DonkeyMonkeyHit** [comment]
Все, пофиксил, проблема была в java и лаунчере. Благодарю за помощь

**Comment by Bjottt** [comment]
average

**Comment by mr-nv** [comment]
> MMC по непонятным не причинам крашит если включен forge

сделай инстанс с пустой 1.12.2, запусти игру (не оффлайн)
потом когда игра запустится закрой ее, добавь фордж и снова запусти игру (опять же не оффлайн)
после этого можешь и в оффлайне запускать и че угодно делать
